apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xusers.keycloak.platformref.upbound.io
spec:
  compositeTypeRef:
    apiVersion: keycloak.platformref.upbound.io/v1alpha1
    kind: XUser
  mode: Pipeline
  pipeline:
    - functionRef:
        name: upbound-platform-ref-aws-cnoecompose-keycloak-user
      step: compose-keycloak-user
    - functionRef:
        name: crossplane-contrib-function-auto-ready
      step: crossplane-contrib-function-auto-ready
